### PR TITLE
Yaml support

### PR DESCRIPTION
**Pull request by ua-sopra-steria**
The APIDefintion class is modified so it can parse Swagger Yaml files when the Swagger file must be modified (due to the backendBasepath parameter being set). For version 7.7, then the changed Swagger file will also be saved in Yaml format, but for earlier versions Json is used. One note though, is that the conversion from Yaml to Json will only take place if the logic to replace backend host is invoked (backendBasepath set and replaceHostInSwagger is true). We could consider to always change Yaml to Json for version 7.6, but I'm not sure it is worth the effort?

3 new test cases have been added.

For version 7.6 some of the existing test cases failed in my setup:
* WSDLFromURLDirectTestIT
Expected RC was: 0 but got: 35
* WSDLFromURLRefFileInConfigurationTestIT
Expected RC was: 0 but got: 35
* WSDLFromURLRefFileTestIT
Expected RC was: 0 but got: 35

However, sometimes they did succeed, so it could be something with my Gateway instance.

For version 7.7 I had to modify some of the test cases:
* OutboundBasicAuthTestIT and OutboundSSLTestIT
password does not seem to be returned from the API Manager

Still some test are failing:
* OutboundMethodLevelTestIT, OutboundSSLTestIT, and OutboundBasicAuthTestIT (Expected RC was: 10 but got: 0)
The promote tool detects that the API Definition has changed (which is not expected in the test case) because of the following:
```
Changed property: authenticationProfiles [
Desired: [
    AuthenticationProfile [name=HTTP Basic outbound Test 116, isDefault=false, parameters={password=password, username=usernameabc}, type=http_basic], 
    AuthenticationProfile [name=_default, isDefault=true, parameters={}, type=none]]
Actual: [
    AuthenticationProfile [name=HTTP Basic outbound Test 116, isDefault=false, parameters={_id_=0, username=usernameabc}, type=http_basic], 
    AuthenticationProfile [name=_default, isDefault=true, parameters={_id_=1}, type=none]]]
```
The issue seems to be the parameers attribute in the Actual profile which contains a property named "_id_". Is this due to a change from 7.6 to 7.7?
* Finally the RollbackTestIT test case fails with "Expected RC was: 35 but got: 0".

### CODE REVIEW

**Comment by ua-sopra-steria** [comment]
Hi @cwiechmann,

The test ImportAndChangeBackendBasepathYamlTestIT fails because an error message is returned when importing an API:
```
Error creating API-Proxy. Unexpected response from API-Manager: HTTP/1.1 500 Internal Server Error {"errors":[{"code":500,"message":"Internal server error"}]}. Last request: 'POST POST https://localhost:8075/api/portal/v1.3/proxies/ HTTP/1.1'. Please check the API-Manager traces.
```
The test succeeds on my installation. Are there any error messages in the API Manager log files?

**Comment by cwiechmann** [comment]
@ua-sopra-steria, the tests on the develop-Branch were executed on 7.6.2 SP4. But in the failed test-cases I don't see this line logged:
`Converting Yaml to Json as Yaml is not supported by this API Manager version!`
Maybe that's the reason, why the two Test-Cases fail.

**Comment by cwiechmann** [comment]
I'm even good not supporting YAML at all in version below 7.7

**Comment by ua-sopra-steria** [comment]
@cwiechmann "... the tests on the develop-Branch were executed on 7.6.2 SP4..."

If the tests run on 7.6.2, then why does the framework return that API Manager version is 7.7?
`10549  INFO  er.APIManagerAdapter| API-Manager version is: 7.7.0`

In the test case I use the method `APIManagerAdapter.hasAPIManagerVersion()` to bypass certain tests if API Manager is not version 7.7 (or higher).
Is that the wrong way to do this?

**Comment by cwiechmann** [comment]
> If the tests run on 7.6.2, then why does the framework return that API Manager version is 7.7?
That's a really good question. Seems at a certain point a merge-action has overwritten the correct version 7.6.2-SP4 with 7.7. 
I changed that. 

However, concerning support for YAML we made some significant changes in the architecture during the API-Management Hackathon in Paris to support different ways to create the "Desired"-API instance. 

For now, using JSON-Config-Files and Input-Streams. 
We did this to make it possible to provide a Swagger-Promote REST-API (as a promotion Service sitting in Front of the API-Manager), which takes in a POST-Call including all required information. 

For that we implemented a generic factory, that selects the correct Config-Handler and I believe it makes sense, to implement based on that another Config-Handler which is then made to support YAML-Config files incl. a YAML-Based Swagger-Definition.
Hence, I don't believe it is worth now to merge this Pull-Request.

https://github.com/axwayhackathon/apimanager-swagger-promote

**Comment by ua-sopra-steria** [comment]
Agree.
Looks cool with the new REST interface for the promote tool.

**Pull request closed without merging**
